### ISSUE TITLE
Support Deno task

### ISSUE THREAD

**Issue by jellydn** [antfu-collective/ni#119]
### Clear and concise description of the problem

# What
Support Deno task

# Why

Deno support tasks on deno.json which is similar with "scripts" on package.json. More detail on https://deno.land/manual@v1.28.3/tools/task_runner

For example:

{
  "tasks": {
    "data": "deno task collect && deno task analyze",
    "collect": "deno run --allow-read=. --allow-write=. scripts/collect.js",
    "analyze": "deno run --allow-read=. scripts/analyze.js"
  }
}

### Suggested solution

# How

We could detect that's running inside Deno project if has deno.json

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Codex-** [comment]
I know this was marked as not planned but I'd love to see this 👀

**Comment by michaelwschultz** [comment]
@Codex- this works now. Make sure you update to the latest version of deno and antfu/ni
