### ISSUE TITLE
More environment variables that override config

### ISSUE THREAD

**Issue by FossPrime** [antfu-collective/ni#158]
### Clear and concise description of the problem

NI_CONFIG_FILE is not enough as it requires a config file to be made, which involves writing a scripts and doing file operations.

### Suggested solution

Package.json would work fine aswell
```json-with-comments
{
  "ni": "pnpm" // Global agent doesnt ever make sense in a package.json
}
```

### Alternative

NI_CONFIG_FILE
NI_DEFAULT
NI_GLOBAL

### Additional context

Stackblitz supports both setting env vars in a config file... or even through package.json

https://stackblitz.com/edit/vitejs-vite-eya5pj?file=package.json

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by a1mersnow** [comment]
There are only two config properties now: `globalAgent` and `defaultAgent`.

Like what you said, `globalAgent` doesn't make sense in a package.json.

While in a project, there are two cases:
- with lock file, then we can automatically detect the agent
- without lock file, we will be prompted for the agent

Both cases are well handled by today's codebase, so I couldn't see any benefit from your suggestion.

**Comment by ghostdevv** [comment]
I would also like this feature, so that I can configure the env var in my main dotfiles rather than having to add another file
