### ISSUE TITLE
Use `package-manager-detector` in this library

### ISSUE THREAD

**Issue by benmccann** [antfu-collective/ni#218]
### Clear and concise description of the problem

There are lots of places like create-svelte, svelte-add, shadcn-svelte, changesets, etc. where we've needed to detect the user's package manager. We end up duplicating this logic or using other packages, which are way too heavy

### Suggested solution

I would love if the code to detect the user's preferred package manager were refactored out into a separate callable package. This repository could be made into a monorepo holding both packages with the CLI calling the library

### Alternative

There is a `preferred-pm` package, but it has 24 dependencies: https://npmgraph.js.org/?q=preferred-pm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by userquin** [comment]
https://github.com/userquin/package-manager-detector (will be tranferred to antfu collective)

**Comment by userquin** [comment]
released initial version v0.0.1: https://github.com/antfu-collective/package-manager-detector/releases

**Comment by benmccann** [comment]
Amazing! Thank you @userquin!

I've renamed this issue to track the remaining portion of using `package-manager-detector` here
