### ISSUE TITLE
New `nd` `ns` `nt` `nb` shortcut commands

### ISSUE THREAD

**Issue by musicq** [antfu-collective/ni#221]
### Clear and concise description of the problem

`nr` is a common shortcut for running any scripts. But most times we will be running these commands during development

- nr dev
- nr start
- nr test
- nr build

### Suggested solution

Usually, I'll add some aliases to my terminal config

```shell
alias nd="nr dev"
alias nt="nr test:w || nr test"
alias nb="nr build"
```

But I'm thinking it would be good if `ni` provides it by default. 

If worrying about naming conflicts https://github.com/antfu-collective/ni/issues/33, I think `ni` can support a more generalized solution, like allowing user to configure these aliases in the `.nirc` file. But seems like to make no difference than configuring in a `.zshrc` file.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Thanks but I believe those local aliases are good enough. We no longer add new commands.
