### ISSUE TITLE
ni and nci fail with version 0.22.2

### ISSUE THREAD

**Issue by gaetan-shopopop** [antfu-collective/ni#224]
### Describe the bug

When running `nci` or `ni` with version 0.22.2 installed globally on any project (yarn or npm based), the command does nothing and exit quickly without output.
This failed in our github actions with a message Process completed with exit code 1 but without more informations.

When reverting to 0.22.1 with `npm install -g @antfu/ni@0.22.1`, there is no issue.

Is there a verbose mode or something llike that to get more informations from these commands ?

### Reproduction

Any project with a valid package.json seems enough to reproduce

### System Info

```Shell
System:
    OS: Linux 6.5 Linux Mint 21.3 (Virginia)
    CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz
    Memory: 5.41 GB / 15.35 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.14.0 - ~/.nvm/versions/node/v20.14.0/bin/node
    Yarn: 1.22.22 - /usr/bin/yarn
    npm: 10.7.0 - ~/.nvm/versions/node/v20.14.0/bin/npm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by mancuoj** [comment]
same here

**Comment by real34** [comment]
I confirm the issue, and the workaround (pinning the version).

Here are a simple package.json + Dockerfile for reproduction with `docker build .` if it can help:
```
{
  "name": "repro",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "echo \"Hello\""
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "axios": "^1.7.4"
  }
}
```
```
FROM node:20.16-alpine

WORKDIR /project

COPY . /project
RUN npm install -g @antfu/ni
# RUN npm install -g @antfu/ni@0.22.1

RUN nci --frozen

ENTRYPOINT ["nr"]
CMD [ "start" ]
```

**Comment by PAN-Ziyue** [comment]
same
