### ISSUE TITLE
What's the alternative for `npm create`?

### ISSUE THREAD

**Issue by lamualfa** [antfu-collective/ni#234]
### Clear and concise description of the problem

Can't find any guide to do `npm create` in ni. I've tried `nr create <package-name>` still doesn't work.

### Suggested solution

Add examples if it's supported. Otherwise, please give a warning about it.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by userquin** [comment]
You can use `na`:
- `mkdir <repo-name> && na init` (init)
- `na create <create-package-dep>` (`na create vite`)

**Comment by lamualfa** [comment]
> You can use `na`:
> 
> * `mkdir <repo-name> && na init` (init)
> * `na create <create-package-dep>` (`na create vite`)

Oh. Never used it before and never knows that alias. Thanks.

Should we add the `npm create` example to the doc? It's often used when setups most projects.

**Comment by userquin** [comment]
it is there, not for `create`, you can check https://github.com/antfu-collective/ni?tab=readme-ov-file#na---agent-alias
